schema_version = "1.0.0"

id = "gzr_custom_keymap"
name = "GZR Custom Keymap"
tagline = "Custom key maps for improved workflow"
version = "1.0.0"
type = "add-on"

maintainer = "KRACT <developer@kract.jp>"
copyright = [ "KRACT" ]

license = ["SPDX:GPL-3.0-or-later"]

blender_version_min = "4.2.0"

website = "https://github.com/kract/blender-addons/tree/main/gzr-custom-keymap"
tags = ["3D View", "User Interface", "Keymap"]

[permissions]
files = "Access to customize keymaps"

[build]
optimized_size = true

