schema_version = "1.0.0"

id = "subamo"
name = "Subamo"
tagline = "Automatically organize Blender backup files into backup folder"
version = "1.0.1"
type = "add-on"

maintainer = "KRACT Studio <studio@kract.jp>"
copyright = [ "KRACT" ]

license = ["SPDX:GPL-3.0-or-later"]

blender_version_min = "4.2.0"

website = "https://kgx.jp/subamo"
tags = ["System"]

[permissions]
files = "Move backup files to organized folder structure"

[build]
optimized_size = true