schema_version = "1.0.0"

id = "langswap"
name = "LangSwap"
tagline = "Quickly switch between multiple languages with a single key press"
version = "1.0.0"
type = "add-on"

maintainer = "KRACT Studio <studio@kract.jp>"
copyright = [ "KRACT" ]

license = ["SPDX:GPL-3.0-or-later"]

blender_version_min = "4.2.0"

website = "https://github.com/kract/blender-addons/tree/main/langswap"
tags = ["System", "User Interface"]

[permissions]
# No special permissions required for this add-on

[build]
optimized_size = true

