schema_version = "1.0.0"

id = "wizender"
name = "Wizender"
tagline = "Magically configure render settings based on project filename"
version = "1.0.1"
type = "add-on"

maintainer = "KRACT <developer@kract.jp>"

license = ["SPDX:GPL-3.0-or-later"]

blender_version_min = "4.2.0"

website = "https://github.com/kract/blender-addons/tree/main/wizender"
tags = ["Render", "System"]

[permissions]
files = "Output render files to project directories"

[build]
optimized_size = true