schema_version = "1.0.0"

id = "versave"
name = "Versave"
tagline = "Enhanced incremental save with proper versioning format and integrated version manager"
version = "1.0.1"
type = "add-on"

maintainer = "KRACT Studio <studio@kract.jp>"
copyright = [ "KRACT" ]

license = ["SPDX:GPL-3.0-or-later"]

blender_version_min = "4.2.0"

website = "https://kgx.jp/versave"
tags = ["System"]

[permissions]
files = "Save versioned blend files to disk"

[build]
optimized_size = true