schema_version = "1.0.0"

id = "viewcam"
name = "Viewcam"
tagline = "Set current viewport view to active camera instantly"
version = "1.0.0"
type = "add-on"

maintainer = "KRACT <developer@kract.jp>"

license = ["SPDX:GPL-3.0-or-later"]

blender_version_min = "4.2.0"

website = "https://github.com/kract/blender-addons/tree/main/viewcam"
tags = ["3D View", "Camera"]

[permissions]
# No special permissions required for this add-on

[build]
optimized_size = true