schema_version = "1.0.0"

id = "keymap_toolkit"
name = "Keymap Toolkit"
tagline = "Customize Blender keymaps by overriding default key bindings"
version = "0.0.1"
type = "add-on"

maintainer = "KRACT <developer@kract.jp>"

license = ["SPDX:GPL-3.0-or-later"]

blender_version_min = "4.2.0"

website = "https://github.com/kract/blender-addons/tree/main/keymap-toolkit"
tags = ["3D View", "User Interface", "Keymap"]

[permissions]

[build]
optimized_size = true

