schema_version = "1.0.0"

id = "keymap_toolkit"
name = "Keymap Toolkit"
tagline = "Custom keymap configuration for Blender"
version = "1.0.0"
type = "add-on"

maintainer = "KRACT <developer@kract.jp>"

license = ["SPDX:GPL-3.0-or-later"]

blender_version_min = "4.2.0"

website = "https://github.com/kract/blender-addons/tree/main/keymap-toolkit"
tags = ["Keymap", "User Interface"]

[permissions]
# No special permissions required for this add-on

[build]
optimized_size = true

